"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
	up: (queryInterface, Sequelize) => {
		return queryInterface.bulkInsert("Menus", [
			{
				id_kategori: 1,
				nama_menu: "Mie Bakso Cincang Tetlan",
				harga: 25000,
				deskripsi:
					"Nikmati sensasi mie bakso dengan cincangan tetlan yang lezat.",
				gambar: "mie_bakso_cincang_tetlan.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 1,
				nama_menu: "Mie Bakso Cincang",
				harga: 25000,
				deskripsi: "Mie bakso dengan cincangan daging yang menggugah selera.",
				gambar: "mie_bakso_cincang.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 1,
				nama_menu: "Mie Bakso Halus",
				harga: 22000,
				deskripsi: "Mie bakso dengan tekstur halus yang memanjakan lidah.",
				gambar: "mie_bakso_halus.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 1,
				nama_menu: "Mie Bakso Telur Iga",
				harga: 30000,
				deskripsi: "Mie bakso dengan tambahan telur dan iga yang kaya rasa.",
				gambar: "mie_bakso_telur_iga.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 1,
				nama_menu: "Mie Bakso Telur",
				harga: 25000,
				deskripsi: "Mie bakso dengan telur yang menambah kelezatan.",
				gambar: "mie_bakso_telur.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 1,
				nama_menu: "Mie Bakso Urat Iga",
				harga: 25000,
				deskripsi: "Mie bakso dengan urat dan iga yang gurih.",
				gambar: "mie_bakso_urat_iga.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 1,
				nama_menu: "Mie Bakso Urat Iga",
				harga: 30000,
				deskripsi: "Mie bakso dengan urat dan iga yang menggugah selera.",
				gambar: "mie_bakso_urat_iga.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 1,
				nama_menu: "Mie Bakso Urat Tetlan",
				harga: 25000,
				deskripsi: "Mie bakso dengan urat dan tetlan yang lezat.",
				gambar: "mie_bakso_urat_tetelan.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 1,
				nama_menu: "Mie Bakso Urat",
				harga: 25000,
				deskripsi: "Mie bakso dengan urat yang kenyal dan nikmat.",
				gambar: "mie_bakso_urat.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 5,
				nama_menu: "Jus Alpukat",
				harga: 25000,
				deskripsi: "Jus alpukat segar yang creamy dan menyehatkan.",
				gambar: "alpukat.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 5,
				nama_menu: "Bubblegum",
				harga: 25000,
				deskripsi: "Minuman bubblegum yang manis dan menyegarkan.",
				gambar: "bubblegum.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 5,
				nama_menu: "Es Jeruk",
				harga: 25000,
				deskripsi: "Es jeruk segar yang menyegarkan dahaga.",
				gambar: "esjeruk.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 5,
				nama_menu: "Jus Mangga",
				harga: 25000,
				deskripsi: "Jus mangga manis yang menyegarkan.",
				gambar: "mangga.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 5,
				nama_menu: "Melon Orange Squash",
				harga: 25000,
				deskripsi: "Minuman squash melon dan jeruk yang segar.",
				gambar: "melon_orange_squash.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				id_kategori: 5,
				nama_menu: "Ocean Blue",
				harga: 25000,
				deskripsi:
					"Minuman Ocean Blue yang menyegarkan dengan warna biru yang menarik.",
				gambar: "ocean_blue.png",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		]);
	},
	down: (queryInterface, Sequelize) => {
		return queryInterface.bulkDelete("Menus", null, {});
	},
};
